In [1]:
#1
import numpy as np
empty_array = np.empty((2, 2))

full_array = np.full((3, 3), 29)

print("Empty Array:")
print(empty_array)

print("\nFull Array:")
print(full_array)

Empty Array:
[[5.85135267e-312 5.85135267e-312]
 [5.85135267e-312 3.94476225e-103]]

Full Array:
[[29 29 29]
 [29 29 29]
 [29 29 29]]


In [12]:
#2
n_arr= np.array([[10.5, 22.5, 3.8],[23.45, 50, 78.7],[41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])


Given array:
[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]
 [41.     nan   nan]]

Remove all rows containing non-numeric elements
[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]]


In [14]:
#3
arr = np.array([[2, 8, 2, 9],[9, 2, 9, 4],[4, 2, 9, 7],[2, 9, 4, 3]])
output = repr(arr).count("2, 9")
print(output)

4


In [15]:
#4
arr = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(arr)

print("Most frequent value in the above array:")
print(np.bincount(arr).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


In [18]:
#5
arr1 = np.array([3, 2, 1])
arr2 = np.array([5, 9, 2])
   
print ("1st array : ", arr1)  
print ("2nd array : ", arr2)  
   
out_arr = np.add(arr1, arr2)  
print ("added array : ", out_arr)  

1st array :  [3 2 1]
2nd array :  [5 9 2]
added array :  [ 8 11  3]


In [19]:
#6
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition = arr > 5
indices = np.where(condition)

print("Original Array:")
print(arr)

print("\nIndices where the condition is satisfied:")
print(indices)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

Indices where the condition is satisfied:
(array([5, 6, 7, 8, 9], dtype=int64),)


In [20]:
#7
matrix = np.array([[1, 2],[3, 4]])
scalar = 2
result_matrix = matrix * scalar

print("Original Matrix:")
print(matrix)

print("\nScalar:")
print(scalar)

print("\nResult Matrix (Matrix multiplied by Scalar):")
print(result_matrix)

Original Matrix:
[[1 2]
 [3 4]]

Scalar:
2

Result Matrix (Matrix multiplied by Scalar):
[[2 4]
 [6 8]]


In [25]:
#8
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

reshaped_array = a.reshape(3,2)
print("Original Array:")
print(a)

print("\nReshaped Array :")
print(reshaped_array)

Original Array:
[[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]]

Reshaped Array :
[[2.5  3.8 ]
 [1.5  4.7 ]
 [2.9  1.56]]


In [26]:
#9
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

boolean_array = a == 1
print("Binary Array:")
print(a)

print("\nBoolean Array:")
print(boolean_array)

Binary Array:
[[1 0 0]
 [1 1 1]
 [0 0 0]]

Boolean Array:
[[ True False False]
 [ True  True  True]
 [False False False]]


In [28]:
#10
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8],[9, 10]])

horizontal_stack = np.hstack((array1, array2))
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nHorizontal Stacking Result:")
print(horizontal_stack)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Horizontal Stacking Result:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [35]:
import random
print("Random integers between 0 and 9: ")
for i in range(1, 10):
    y = random.randrange(9)
    print(y)

Random integers between 0 and 9: 
2
8
8
0
4
1
4
4
8


In [39]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[2, 3, 4],
              [5, 6, 7],
              [8, 9, 10]])

result = np.multiply(a, b)

print("Matrix A:")
print(a)

print("\nMatrix B:")
print(b)

print("\nMatrix Multiplication Result:")
print(result)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Matrix Multiplication Result:
[[ 2  6 12]
 [20 30 42]
 [56 72 90]]
